import type { NextPage } from 'next';
import Head from 'next/head';
import TimeTrackingDashboard from '../components/time-tracking-dashboard/TimeTrackingDashboard';

const Home: NextPage = () => {
  return (
    <div className='home'>
      <Head>
        <title>Time tracking dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/assets/images/favicon-32x32.png' />
      </Head>
      <main>
        <TimeTrackingDashboard />
      </main>
    </div>
  );
};

export default Home;
